### ISSUE TITLE
Notification to Fix STATE NOT FOUND Error on Website - Subject-Card

### ISSUE THREAD

**Issue by moking55** [textures1245/nuxt-course-mju-enrollment#1]
Dear @textures1245 ,

We regret to inform you that some of your website visitors are encountering a STATE NOT FOUND error message when attempting to access the "subjects/subject-card" path on your website. This can be frustrating for your users, and can lead to a negative user experience on your website.

As a responsible website owner, we urge you to take prompt action to fix this issue. You may need to review your website code and configuration to identify the root cause of this error, and make the necessary changes to ensure that your website is fully functional and accessible to all users.

Remember, a smooth user experience is key to building a loyal and engaged audience, so investing in the maintenance and optimization of your website is essential for your long-term success.

Thank you for your attention to this matter.

Best regards,
@moking55

**Comment by textures1245** [comment]
Dear @moking55,

Thank you for taking the time to reach out to us regarding the issue you experienced with our service. We understand how frustrating it can be when a state is not found in our system, and we appreciate your patience while we worked to resolve this issue.

We apologize for any inconvenience this may have caused you, and we want to assure you that we take every effort to ensure that our service is fully functional and up-to-date. Our technical team has been notified of the issue, and they are actively working to investigate and resolve the root cause of the problem.

In the meantime, we suggest that you try entering your state again in a few days, as the issue may have already been resolved. If you continue to experience any difficulties, please don't hesitate to contact us again and we will do our best to assist you.

Once again, thank you for bringing this issue to our attention. We value your business and appreciate your feedback. Please let us know if there is anything else we can do to assist you.

Best regards,
@textures1245
